### ISSUE TITLE
No activation in the Encoder 1st Layer

### ISSUE THREAD

**Issue by mr-ubik** [houssamzenati/Efficient-GAN-Anomaly-Detection#11]
No activation layer or nonlinearity is found in the block of code describing the first layer of the Encoder.

**Comment by houssamzenati** [comment]
Hi and thanks, 

Well found, I will change it rightaway, did you notice any gap in performance or reconstruction quality by adding a nonlinearity? Without it this layer is somehow useless. Please let me know

Thanks a lot,
Houssam

**Comment by mr-ubik** [comment]
Unfortunately, I did not try it without it.
