### ISSUE TITLE
anomalous label for the experiment

### ISSUE THREAD

**Issue by JiweiTian** [houssamzenati/Efficient-GAN-Anomaly-Detection#12]
hi，
parser.add_argument('--label', nargs="?", type=int, help='anomalous label for the experiment')
--label=<0, 1, 2, 3, 4, 5, 6, 7, 8, 9>
I don't know the real meaning of anomalous labels. Does the label choice (0-9) have some effect on the detection performance?

**Comment by sxooler** [comment]
@JiweiTian: Refer to the original paper for MNIST dataset generation (Experiments section) [https://arxiv.org/abs/1802.06222](https://arxiv.org/abs/1802.06222)

You can choose whatever number you prefer to be an anomalous one. The rest (9 digits) is considered normal examples then. Or you can follow the generation in the paper - generating 10 different dataset by making each digit as anomaly class in exactly one of these datasets.

Detection performance is a good question. When you check the original paper and look at performance graph for MNIST dataset, you can see varying AUC results.  I'm guessing it's easier to detect "0" or "2" anomaly classes than "1" or "7" anomaly classes.

**Comment by houssamzenati** [comment]
@sxooler Many thanks for your reply, which really is of great help and of insight!
