### ISSUE TITLE
A question about the feature

### ISSUE THREAD

**Issue by pangwenfeng** [houssamzenati/Efficient-GAN-Anomaly-Detection#16]
Hello, thanks for your nice work! I have a question that has you tried to utilize the feature extracted from the latent layer? i.e. the output of E(x). Because in the works related to autoencoder, the authors usually used the latent layer as the feature extractor, but in the work related to BiGan, I do not find this kind of usages, though BiGan is equal to an autoencoder in the optimal situation. Maybe I do not explain my question here clearly, it is so nice if I can send you the email if you don't mind.

**Comment by houssamzenati** [comment]
Hi,

I think the feature extractor is needed for the discriminator and not the encoder so I have not tried it.

Yes feel free to send my an email and do not hesitate to check out the updated version of this work as well which is publised at ICDM 2018: https://arxiv.org/pdf/1812.02288.pdf

Look forward to reading from you soon
