### ISSUE TITLE
How the precision range was calculated?

### ISSUE THREAD

**Issue by shekharbiradar** [houssamzenati/Efficient-GAN-Anomaly-Detection#17]
First of all thanks for the amazing paper. Quickly wanted to know how the range for the below metrics was found. When i run the code, i see absolute value.
Our Modelσ 0.9200 ± 0.0740 0.9582 ± 0.0104 0.9372 ± 0.0440

**Comment by houssamzenati** [comment]
It was the variance across different seeds if I am not mistaken, apologies for answering so late...
