### ISSUE TITLE
Get_shape_input

### ISSUE THREAD

**Issue by islrnd** [houssamzenati/Efficient-GAN-Anomaly-Detection#18]
could you kindly explain why the shape of dataset is mentioned as None,121 in get_shape_input function?

**Comment by shekharbiradar** [comment]
There are 121 columns (after you do one hot encoding)

**Comment by islrnd** [comment]
> There are 121 columns (after you do one hot encoding)

Thank you so much for your answer.. Could you also help in me in understanding get_valid function?

def get_valid(label=0, scale=False, *args):
    """Get validation dataset for KDD 10 percent"""
    return None

Why it is returning None?

**Comment by houssamzenati** [comment]
Details on the KDD setup are given in the DAGMM paper we follow to compare our method with theirs
