### ISSUE TITLE
Datasets with other dimensions

### ISSUE THREAD

**Issue by pfreitasaf** [houssamzenati/Efficient-GAN-Anomaly-Detection#19]
Hello Mr.,

First of all, congratulations on your work! It is very interesting and insightful.
I was able to run your code with the kddcup99 dataset. However, I would like to know if you could give me some help and directions on how to adapt your code for other datasets with different dimensions. For example, what I would have to do if I want to use only a few features of the kddcup99 dataset, so I have  15 features instead of 121?

Thank you very much for your help and assistance!
Best regards,
Paulo

**Comment by houssamzenati** [comment]
HI Paulo and apologies for answering lately, I guess you would have to adjust the size of the MLP layers and the preprocessing scripts as well. Hope this will help

**Comment by pfreitasaf** [comment]
Hello,
Thank you for your reply! I eventually was able to made the necessary adjustments!
The paper that I was working on has just been published by IEEE Internet of Things Journal. I cite two of your papers in my work. :) Please find the complete version of my paper: https://ieeexplore.ieee.org/document/9199878
