### ISSUE TITLE
At train AnoGAN with MNIST data, Does the train set and test set all contain only normal data?

### ISSUE THREAD

**Issue by bemoregt** [houssamzenati/Efficient-GAN-Anomaly-Detection#3]
Hi, @houssamzenati 
 
In the case of Anomaly Gan, I knew that it trained with only normal datasets.

At train AnoGAN with MNIST data, Does the train set and test set all contain only normal data?

Or are both normal + abnormal divided into folders? 
I wonder.

form @bemoregt.

**Comment by houssamzenati** [comment]
Hi,

Only normal data during training and both anomalous and normal during testing. 
Please refer to our pre-published article on arxiv for the experimental setup information,

https://arxiv.org/abs/1802.06222

Houssam
