### ISSUE TITLE
Hi, I have something problem in main.py

### ISSUE THREAD

**Issue by kwlee1201** [houssamzenati/Efficient-GAN-Anomaly-Detection#5]
I try to run your program today.
When I use this command "python main.py gan kdd run --nb_epochs=1 --label=1",
it will be error.
The following message is the content of this error
"""
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    parser.add_argument('--d', nargs="?", default=1, defaulttype=int, help='degree for the L norm')
  File "/anaconda3/lib/python3.6/argparse.py", line 1334, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument '**defaulttype**'
"""
This is caused by the "**defaulttype**".
I think it is a mistake, since other parameters is used "**type**", but the parameter "--d" is not.
Is it right?

k.w.

**Comment by mhmoodlan** [comment]
yes, i had the same problem. Just replace 'defaulttype' with 'type' and it should run fine.

**Comment by kwlee1201** [comment]
thanks. :)

**Comment by houssamzenati** [comment]
Thank you both!
